### ISSUE TITLE
snapraid-btrfs-runner - cleanup guidance?

### ISSUE THREAD

**Issue by fmoledina** [automorphism88/snapraid-btrfs#10]
Hello,

I'm revisiting snapraid-btrfs as I'm adapting the [snapraid-runner](https://github.com/Chronial/snapraid-runner) tool to work with it. My tool is aptly named [snapraid-btrfs-runner](https://github.com/fmoledina/snapraid-btrfs-runner). With this tool I implement a basic automated sync + scrub workflow using snapraid-btrfs.

I'd like to implement a cleanup yes/no option in the configuration that's exposed to users, and if the sync and scrub are successful, run a `snapraid-btrfs cleanup`. Is it as simple as that or are there any special considerations that I should account for depending on how users want to specify `--cleanup` algorithms or `--use-snapshot-all`? Thanks.

**Comment by automorphism88** [comment]
Hi,

As I understand your question, yes, it should indeed be as simple as just running `snapraid-btrfs cleanup`. That's what I do myself, and it's how the command is designed to be used.

Specifying a cleanup algorithm with the `--cleanup` option will only affect the `snapper cleanup` command, which is not run by `snapraid-btrfs cleanup`. Instead, `snapraid-btrfs cleanup` uses `snapper rm` to delete any snapshots created by `snapraid-btrfs` which are older than the one which a sync was last successfully completed with (or older than whatever snapshot you specify with `--use-snapshot` or `--use-snapshot-all`, but the default for the `cleanup` command is `sync`, and I don't think it's terribly useful to change that default, but it's allowed because there's not really a reason not to allow it). Any snapshots not created by `snapraid-btrfs` (i.e., without the snapraid-btrfs snapper userdata key defined) will always be ignored. (The `cleanup-all` command does the same thing, but using snapshot `0` rather than `sync`, so that it deletes all snapshots with the userdata key defined, and it does ignore the `--use-snapshot` and `--use-snapshot-all` options.) The `--cleanup` option really only exists for the sake of completeness, since I wanted to pass through all the options snapper offers when creating snapshots, and I don't personally use it myself.

The behavior above should be explained by the output of `snapraid-btrfs --help`, so if that was less than clear, I'd welcome any suggestions you might have for improving the documentation (though I'd understand if you just wanted to double check). I'd also welcome any suggestions for how the script's functionality might be improved to better work with your tool.

A few caveats:

- If you're using `snapraid-btrfs pool`, make sure to run it in between the sync and the cleanup. Otherwise you'll end up with broken symlinks that point to deleted snapshots.
- Use caution when automating `snapraid-btrfs`, and keep an eye on it to make sure it's doing what you expect. I wrote `snapraid-btrfs` primarily for my own use, and test it on my own system. It should be considered experimental software, and as stated in the license, there is no warranty. Bug reports are, of course, welcome.
- The above describes the current behavior of the `cleanup` command. Given the experimental nature of `snapraid-btrfs`, it's recommended to use the latest version. The most recent version, released less than 24 hours ago, comes with improvements for both the `scrub` and `cleanup` commands. I'd been thinking it would be nice to add a changelog to better document those improvements, but hearing about your tool makes that seem like a higher priority. In the meantime, you can look at how the output of `snapraid-btrfs --help` has changed, since that's kept up to date with any changes in the script's behavior.

Thanks for opening this issue. It's interesting to hear how you're making use of snapraid-btrfs. I'm going to convert this issue into a discussion, but please feel free to follow up if you have any other questions.
