### ISSUE TITLE
Questions re MergerFS and Timeshift

### ISSUE THREAD

**Issue by zilexa** [automorphism88/snapraid-btrfs#11]
I read through the readme and wonder if you foresee any issues when using MergerFS to pool three (BTRFS) drives (4TB, 5TB harddrives and a 1TB SSD). Each drive as you recommend will have a single snapshot containing data. And the mounted path of those volumes will be used by MergerFS to create the datapool. 

Second: I preferred Timeshift over Snapper on my laptops because Timeshift creates a subvolume for its snapshots, where Snapper creates them in each subfolder (that never made any sense to me). When using your tool, will it also splatter my filesystems with hidden subfolders?

And if I may a 3rd question: any recommendations for the BTRFS mount options of the data drive? Would you recommend the use of compression? I currently use `defaults,noatime,subvol=@data` for SSD and HDDs.

**Comment by fmoledina** [comment]
> I read through the readme and wonder if you foresee any issues when using MergerFS to pool three (BTRFS) drives (4TB, 5TB harddrives and a 1TB SSD). Each drive as you recommend will have a single snapshot containing data. And the mounted path of those volumes will be used by MergerFS to create the datapool.

For what it's worth, I'm a user of `snapraid-btrfs` exactly this way, with multiple drives pooled using MergerFS. I'm slowly converting my XFS drives to BTRFS to take advantage of the features that `snapraid-btrfs` provides across my pool. As with upstream `snapraid`, `snapraid-btrfs` is indifferent to how you populate the drives with data, i.e. using MergerFS.

**Comment by automorphism88** [comment]
I would use MergerFS on the live filesystem and not the snapshots. That's what I do at least, because the whole point of MergerFS in my view is that it's read-write. Specifically, I use it on the subvolume that holds the files SnapRAID processes. I actually mount the root subvolume on my SnapRAID drives because I prefer a flat subvolume layout, rather than having the content file subvolumes be inside the "payload" subvolume, since MergerFS makes the longer path irrelevant. That's just personal preference though. And the only other mount option I use is noatime. If you have a drive that's smaller than your parity drives and contains compressible files then I think it'd make sense to enable zstd compression.

I'm not a huge fan of the snapper subvolume layout with the `.snapshots’ subvolume being located inside the main subvolume, but it's not that big of a deal, and if you really want you can have a snapshots subvolume wherever you want and just mount it at the location snapper is expecting it to be. And no, it's not going to create any hidden folders or subvolumes outside of that ’.snapshots’ subvolume. You can get rid of everything it's created by just deleting first the snapshots underneath it (at ’.snapshots/1/snapshot’ and so on) and then the ’.snapshots’ subvolume itself. I chose to use snapper because I was using OpenSUSE Tumbleweed at the time so was already familiar with it, and it did everything I needed it to, including handling permissions so you can run snapraid-btrfs as a normal user, and keeping track of the snapshots via the userdata field, so that snapraid-btrfs doesn't need to store its own files anywhere to keep track of things. Avoiding the need for a snapraid-btrfs config file was also a design goal. It's actually caused me quite a bit of trouble though in the sense that most of the maintenance snapraid-btrfs has required has been the result of changes in snapper's behavior and the need to work with both older and newer versions.

**Comment by zilexa** [comment]
Thanks a lot for explaining everything. One major downside for me is that I cannot use subvolumes on the data disks. I have /Users/User1, /Users/User2 ... Etc folders and want to use a different tool to create a timeline of snapshots inside each UserX folder, for example:
Users/User1/.snaps/2020/12/25 for the snapshot of 25th of December. 
I only have 2 main data folders, /Users and /Media. I was thinking of creating subvolumes or nested subvolumes (/data/Users, /data/Media) just to be able to easily snapshot at least the Users folder.

But I understand subvolumes or even nested subvolumes are not supported at all. This would be a reason for me to just use original SnapRAID and accept the downsides that your solution solves.

**Comment by automorphism88** [comment]
> Thanks a lot for explaining everything. One major downside for me is that I cannot use subvolumes on the data disks (I have 2 separate disks purely for Snapraid parity content files)
> On the data disks I have `/Users/User1` and `/Users/User2` ... Etc folders containing the personal data of each user that uses my homeserver as private cloud.
> 
> I only have 2 main data folders, /Users and /Media. I was thinking of creating subvolumes or nested subvolumes (/data/Users, /data/Media) just to be able to easily snapshot (for the benefit of the user, outside of the Snapraid scope) at least the Users folder.
> 
> Preferably I wanted to use a tool to create a timeline of snapshots inside each UserX folder, for example:
> `Users/User1/.snaps/2020/12/25` for the snapshot of 25th of December and so on.
> 
> But now I understand I cannot use that AND use SnapRAID to protect against disk failure.
> Because I understand subvolumes or even nested subvolumes on the data disks are not supported at all. That is a bummer as I cannot serve snapshots to users.
> 
> I do believe this is a desired usecase, to use SnapRAID to protect data disks while not being limited to create "user facing" snapshots of specific folders for end user purposes to go back in time with their personal documents and creations.
> 
> Do you have thoughts on this?

Short answer: Depending on what you want to do, it either already works with `snapraid-btrfs`, or the limitation is with SnapRAID and there's nothing `snapraid-btrfs` can do about it. `snapraid-btrfs` is just a wrapper around `snapraid`, and doesn't stop you from doing anything useful that you could do without it (with exceptions noted in the "Known issues" section of the README).

Long answer: It's fine to use subvolumes on SnapRAID data disks, but all of the files you are syncing (the "data" mentioned in `/etc/snapraid.conf`) need to be in the same subvolume. That's true whether you're using snapraid-btrfs or just plain snapraid. SnapRAID considers btrfs subvolumes to be separate filesystems, as they have separate UUIDs. Therefore, each "data" entry in your snapraid.conf file must correspond to only one subvolume. Any subvolumes mounted underneath will be ignored with a warning message last I checked.

That's only for SnapRAID parity purposes - you're free to have other subvolumes on that drive, including snapshots of the data subvolume, and `snapraid-btrfs` in fact enforces that the content file be stored in a separate subvolume (as explained in the README). You can have your own snapshotting scheme like what you described, and snapraid-btrfs won't interfere with that at all. `snapraid-btrfs` uses a snapper userdata key to keep track of its own snapshots, and will ignore any snapshots it didn't create. You're free to create your own snapshots separately, whether using snapper or not, and `snapraid-btrfs` will manage its snapshots entirely independently.

Whether you use snapraid-btrfs or just plain snapraid, it's not possible for the snapraid parity to protect more than one snapshot at a time. To have parity protect multiple snapshots, the RAID needs to happen either at the filesystem level (btrfs raid) or at the device level (md raid). To use SnapRAID with btrfs, you have to pick a single subvolume for the parity to correspond to. All `snapraid-btrfs` does is to make that subvolume a readonly snapshot that it manages, so that the state of the data subvolume at the time of the sync is preserved.

It sounds like this is a hypothetical setup that you haven't created yet, and not something that you have working with vanilla snapraid but not snapraid-btrfs. Therefore, I'm closing this issue, as it doesn't appear there is any bug or missing functionality in `snapraid-btrfs`. If there's a use case that works with vanilla snapraid but not snapraid-btrfs, please clarify.
