### ISSUE TITLE
snapraid-btrfs does not work nicely with snapraid "autosave"

### ISSUE THREAD

**Issue by zilexa** [automorphism88/snapraid-btrfs#14]
Snapraid-btrfs creates a new snapshot everytime snapraid autosaves the state when syncing. This can lead to a huge amount of snapshots (86 snapshots in a single run), for each time you run snapraid-btrfs. This is not desirable for obvious reasons. 

For now, I disabled this option in snapraid.conf. Is it possible to allow autosaving, without creating new snapshots? It does not make sense to constantly make a new snapshot, the whole idea is to do a sync of 1 snapshot. 

Autosave is a very useful function to protect against power loss/system crash during a sync. 
```
# Automatically save the state when syncing after the specified amount
# of GB processed (uncomment to enable).
# This option is useful to avoid to restart from scratch long 'sync'
# commands interrupted by a machine crash.
# It also improves the recovering if a disk break during a 'sync'.
# Default value is 0, meaning disabled.
# Format: "autosave SIZE_IN_GB"
autosave 150

```

**Comment by automorphism88** [comment]
> Snapraid-btrfs creates a new snapshot everytime snapraid autosaves the state when syncing. This can lead to a huge amount of snapshots (86 snapshots in a single run), for each time you run snapraid-btrfs. This is not desirable for obvious reasons.
> 
> For now, I disabled this option in snapraid.conf. Is it possible to allow autosaving, without creating new snapshots? It does not make sense to constantly make a new snapshot, the whole idea is to do a sync of 1 snapshot.
> 
> Autosave is a very useful function to protect against power loss/system crash during a sync.
> 
> ```
> # Automatically save the state when syncing after the specified amount
> # of GB processed (uncomment to enable).
> # This option is useful to avoid to restart from scratch long 'sync'
> # commands interrupted by a machine crash.
> # It also improves the recovering if a disk break during a 'sync'.
> # Default value is 0, meaning disabled.
> # Format: "autosave SIZE_IN_GB"
> autosave 150
> ```

This doesn't happen for me, and I even tested by changing my own snapraid.conf to have `autosave 1` just to make sure.

Nor is there any reason why it should ever be able to happen, because when `snapraid` autosaves, it doesn't exit, it just saves its status to the content files and resumes the sync/scrub operation. `snapraid-btrfs` runs `snapraid` in the foreground, so it's just waiting and doing nothing until `snapraid` exits. And regardless of autosaving, by the time `snapraid-btrfs` runs `snapraid`, its snapshot creation is complete (except for the fix and touch commands, where it creates pre/post snapshots). When `snapraid` exits, `snapraid-btrfs` has no idea whether it autosaved and doesn't care. Now, on the other hand, if you interrupt the sync with Ctrl+C and then re-run `snapraid-btrfs sync`, by default it will create new snapshots, but if you want to resume with the same set of snapshots, you can re-run `snapraid-btrfs` with `--use-snapshot-all resume`.

If this is indeed somehow happening for you without running `snapraid-btrfs` more than once, to debug it further I would need the debug output (run `DEBUG_FD=3 snapraid-btrfs sync 3>debug.log`) and the output of `snapraid-btrfs ls` (after running the sync that creates more than one snapshot). The debug log will be large, but GitHub allows you to upload gzipped text files, and it will compress extremely well with `gzip -9 debug.log`.

**Comment by zilexa** [comment]
No idea what happened, why I had so many snapshots. Snapraid-btrfs has been running nightly (with cleanup afterwards). I just did a manual run with the command you supplied and I don't see the issue anymore. Only a single snapshot per disk is created.

**Comment by zilexa** [comment]
Just FYI: 
This happened because when you create Snapper config files, by default all options are ON: timeline snapshots. So it will constantly create snapshots, resulting in MANY snapshots. 

Perhaps an idea to add this to your documentation to set everything to "no" in the snapper config files. Otherwise snapper will even create snapshots during syncing..
