### ISSUE TITLE
have you had any fix issues when old snapshots removed ?

### ISSUE THREAD

**Issue by MasterCATZ** [automorphism88/snapraid-btrfs#18]
I had a btrfs disk that refused to mount but when doing a fix I only received 700gb worth of data back because parity failed 
unsure how this could be possible with 5x parity 
thankfully btrfs restore was able to pull the files from the un-mountable disk 

I am wondering if it has something to do with the files only being synced to the snapshot folder path ?  
and once these old snapshots have been pruned back things go sour ?

I noticed snapraid see's the file like this 
/mnt/SnapRaidArray/SRD20NA1B19/.snapshots/3908/snapshot/

I would have thought it would  be looking at them like /mnt/SnapRaidArray/SRD20NA1B19/

**Comment by automorphism88** [comment]
I have fixed multiple failed disks and not had any issues, and I run snapraid-btrfs cleanup after every sync. The snapshot pruning logic should never delete any snapshots that might be needed for a fix. Based on your quoted text below I think I would have been able to help you specify command-line options that would have allowed the fix to succeed. See explanation below the quote.

>I noticed snapraid see's the file like this
/mnt/SnapRaidArray/SRD20NA1B19/.snapshots/3908/snapshot/

>I would have thought it would be looking at them like /mnt/SnapRaidArray/SRD20NA1B19/

That is because when you are fixing, snapraid needs to see the live filesystem and not a readonly snapshot, because fixing is a read-write operation. By default, if you don't specify any command-line options, snapraid tries to fix all drives, so snapraid-btrfs will need to show it the live filesystem for all drives. Then it won't find the files in the snapshots that it needs, unless you import them using the `--import` option. If you know you're fixing a single failed drive, you can pass the `-d` option to snapraid to tell it to only fix that disk, and snapraid-btrfs will notice that and use the live filesystem only for that disk and snapshots for the others. Or, you can use the `--use-snapshot` and `--use-snapshot-all` snapraid-btrfs command-line options to point snapraid to the right snapshots for the right drives, or if all else failed, make your own temporary snapraid.conf file to point to the right snapshots (which is what snapraid-btrfs does automatically).

**Comment by automorphism88** [comment]
Closed because I don't think the script is pruning any snapshots that shouldn't be pruned. It's possible that improvements could be made to the interface or documentation for the fix command.

**Comment by MasterCATZ** [comment]
I use snapper that auto prunes snapshots  

# limits for timeline cleanup
TIMELINE_MIN_AGE="1800"
TIMELINE_LIMIT_HOURLY="24"
TIMELINE_LIMIT_DAILY="14"
TIMELINE_LIMIT_WEEKLY="4"
TIMELINE_LIMIT_MONTHLY="12"
TIMELINE_LIMIT_YEARLY="2"


I used a command like this 

snapraid -d d2 -l ~\fixD2.log fix

but parity was failing ?
why would snapraid be needing to access the old snapshots for ? 


never used 
snapraid-btrfs cleanup
before

**Comment by automorphism88** [comment]
> I use snapper that auto prunes snapshots

If you are running snapper cleanup, or generally running snapper directly in any capacity to delete snapshots, then snapraid-btrfs doesn't control what happens. With a timeline cleanup, snapper will only delete snapshots that are marked as timeline. So it'd be safe as long as you don't tell snapraid-btrfs to create its snapshots as timeline snapshots (which is not the default). The recommended way of cleaning up old snapshots is to use the `snapraid-btrfs cleanup` command, which will safely delete only obsolete snapshots that no longer correspond to any of the parity.

**Comment by MasterCATZ** [comment]
so does snapraid-btrfs cleanup only remove its own snapshots ?
and how would I get snapper to leave snapraid-btrfs snapshots alone and just prune its timeline ones?

**Comment by automorphism88** [comment]
> I used a command like this
> 
> snapraid -d d2 -l ~\fixD2.log fix

You should run the same command but with `snapraid-btrfs` instead of `snapraid` and put the `-d` and `-l` options after `fix` instead of before it (order matters, since options coming before the command are interpreted as `snapraid-btrfs` options rather than `snapraid` pass-through options). Then `snapraid-btrfs` will automatically run `snapraid fix` with a config file that points to the live filesystem for that drive you are fixing and the last synced snapshots for all other data drives.

> but parity was failing ?

`snapraid-btrfs` doesn't do anything with the parity disks.

> why would snapraid be needing to access the old snapshots for ?

Parity alone is not enough to fix a data disk, you need to be able to access the other data disks as well. The total number of disks failed at any block just has to be less than or equal to the number of parities. It only needs to access the snapshots that correspond to the current state of the parity.

> never used
> snapraid-btrfs cleanup
> before

Well then, this definitely isn't a bug with `snapraid-btrfs`, because the only way `snapraid-btrfs` would prune old snapshots is if you used that command.

**Comment by automorphism88** [comment]
> so does snapraid-btrfs cleanup only remove its own snapshots ?

Yes, see the README, snapraid-btrfs keeps track of its own snapshots using a userdata key, and will ignore any snapshots that don't have that userdata key defined. So any snapshots you create on your own with snapper will be ignored, unless you deliberately set that userdata key to make snapraid-btrfs think those are its snapshots. Any behavior not consistent with this would be a bug.

> and how would I get snapper to leave snapraid-btrfs snapshots alone and just prune its timeline ones?

That should be the default behavior, snapper cleanup will only delete snapshots that have the "timeline" cleanup strategy set for them, which snapraid-btrfs will not do unless you explicitly ask it to (see `--help` output).

**Comment by MasterCATZ** [comment]
did not know the parity was being bound directly to the btrfs-snapshots , assumed it was still seeing the same file tree and it was just locking snapraid to a snapshot for reading so live data changes could still be made without it failing 

I will have to start using the cleanup function after syncs

**Comment by automorphism88** [comment]
Please read the README as it seems your issues are being caused by not understanding how snapraid-btrfs works and what it does and doesn't do.

On a more general note and not specifically related to snapraid-btrfs, you should test things like this before you need them. For instance delete some files (that you have backups of just in case) and test whether you can restore them with a fix operation, before you actually need to do that fix because a disk failed.

**Comment by MasterCATZ** [comment]
I tried the cleanup today but it errors out on all of the drives

snapraid-btrfs: WARNING: No synced snapshot found for config SRD1NA1B0 - skipping 

could this be from having timeline snapshots made after the sync snapshot ? 

![Screenshot from 2021-06-08 10-21-37](https://user-images.githubusercontent.com/1857824/121103466-59ce7a00-c843-11eb-84fe-2fd18d729905.png)
