### ISSUE TITLE
Snapraid as non-root

### ISSUE THREAD

**Issue by cmcginty** [automorphism88/snapraid-btrfs#24]
Curious as to why you recommend running as non-root? Obviously, if you run snapraid as non-root you will not have access to files on a multi-users system. So to achieve a complete backup it would make sense to run as root. Did you have a source where it recommends not to run as root?

**Comment by gilgwath** [comment]
I'm not the dev of any of these tools around snapraid, but I have a background in security, so I may be able to answer this question:

1. Principal of the least privilege: Always run things with the least privilege you can. Snapraid does not need any root privileges for any of the things it does, so you should not run it as root.
2. Snapraid processes untrusted input, so there's a risk that there's away to craft input in a way that it is treated as code rather than data and is executed. This code is executed with whatever privileges the process runs as. Since snapraid is written in Python, exploiting such a vulnerability does not take all that much skill.

Maybe the devs have more reasons, but those are the ones that are obvious to me.

Cheers
Gilgwath
