### ISSUE TITLE
snapraid-btrfs interactive prompt

### ISSUE THREAD

**Issue by MasterCATZ** [automorphism88/snapraid-btrfs#4]
for some reason I now keep getting , snapraid-btrfs interactive prompt

I had a drive unmounted to clone / swap out , replaced disk and now keep getting this for every disk

**Comment by MasterCATZ** [comment]
[snapraidbtrfs.debug.txt](https://github.com/automorphism88/snapraid-btrfs/files/3954916/snapraidbtrfs.debug.txt)

snapraid-btrfs -x scrub > ~/Documents/snapraidbtrfs.debug.txt
debug log

**Comment by automorphism88** [comment]
>snapraid-btrfs -x scrub > ~/Documents/snapraidbtrfs.debug.txt
>snapraidbtrfs.debug.txt
> well that failed , got to remember what I used to use to record terminal output

A lot of the terminal output from `snapraid-btrfs` goes to stderr instead of stdout, and the redirection you give is only for stdout, so stderr will still go to the console and not the file. I tried to follow standard UNIX conventions for what output should go to stdout vs stderr, so any deviations from that should be reported as a bug. You're only redirecting stdout to that file with the command you give and I can't tell much from that alone.

If you want to redirect both stdout and stderr to the same file, so that everything you'd otherwise see on the terminal goes to the same file, you can use `&>file` (in bash, or other shells that support this syntax like zsh) or the more verbose `>file 2>1` which should work in any POSIX shell. To redirect just stderr, you can do `2>file`, or to send stdout and stderr to different files, `>file1 2>file2`. The debug output from the `-x` option goes to stderr by default but can be sent to a different fd by setting the `DEBUG_FD` environment variable (inspired by the `BASH_XTRACEFD` variable that does the same thing for the `bash -x` output). So for instance, `DEBUG_FD=3 snapraid-btrfs -xh >stdout.txt 2>stderr.txt 3>debug.txt` would send stdout, stderr, and debug output to different files.

> it would be good if their was also a Last option to select from

What do you mean by that? The `-u` and `-U` options to select snapshots do accept `last` as an argument. Or do you mean it should be an option in the interactive menu that asks you to pick which snapshot to use? You should be given the output of `snapper ls` for that subvolume before being asked to choose, so you can just enter the number you want yourself. That menu only appears for error recovery purposes and while it would be trivially easy to make it possible to specify last, or any of the other strategies supported by `-u` and `-U`, there doesn't seem much point because if you're already looking at the list of snapshots you can just enter the number you want directly. The point of those rules like "last" is to pick snapshots without human intervention, and by the time you get to the menu, that's already failed. That's why the only answers accepted at that point are a valid snapshot number, `new`, or `0` for the live filesystem.

> script ~/Documents/snapraid-btrfs.output.txt
> [snapraid-btrfs.output.txt](https://github.com/automorphism88/snapraid-btrfs/files/3954982/snapraid-btrfs.output.txt)

What am I supposed to be looking for in this file? At 24.1 MB I didn't look through the entire thing, but I did look at the last part and it looks like `snapraid scrub` was run by the script, but failed due to a permission error creating `/home/snapraid.content.lock`. That looks like a problem with your snapraid config regardless of whether it's invoked using snapraid-btrfs. The `/home` directory is a bad place to store a content file, since it's typically owned by root and not writable by others, and even if you chown/chmod the content file itself so the user that runs snapraid has read/write permission, you also need write permission for the directory the content file is in, or snapraid won't be able to create a lock file. Find somewhere else to store the content file, and make sure the user running snapraid has read/write permissions for the directory it's in and not just the content file itself.

I also noticed the huge stderr file had CRLF Windows-style line endings (except on the first line) while the small file with just stdout had normal UNIX LF line endings. I'm not sure how you generated this file, or if you perhaps processed the file in Windows with software that might have changed the line ending style, but that looks really strange and makes me wonder if whatever caused it might have other weird and unanticipated effects.

> snapper 0.8.3
> Ubuntu 19.10
> btrfs-progs v5.2.1

Should be supported, as should Ubuntu 18.04. The `btrfs-progs` version is unlikely to matter since the script never uses the `btrfs` command. Everything is done through snapper. Snapper does use `libbtrfs` from `btrfs-progs` under the hood, but if snapper is working normally when it's run directly, then there shouldn't be any difference when it's invoked by `snapraid-btrfs`.

I'm closing this issue since there don't appear to be any identifiable snapraid-btrfs bugs described here. If it does turn out that `snapraid-btrfs` isn't setting the userdata key for snapshots properly when a sync is run, you can open a separate issue with the relevant information, as requested above.

**Comment by MasterCATZ** [comment]
@automorphism88 

https://drive.google.com/file/d/1Fuf_jGo4H6Q7cVdAvX9I1H1klrzFrBs-/view?usp=sharing

I am talking about it keeps prompting in "interactive mode" instead of auto creating snapshots 

Enter a snapshot (0 for none, n for new, q to quit):

only options are 
0 no snapshot 
( pointless I may as well just run snapraid and have it go nuts through all the snapshots and files being changed) 
n for new
q to quit 

and its annoying pressing "n" for every disk manually 

and their is no option to select last snapshot , 
which would be handy as I have hourly snapshots and most of the time I am minutes away from last snapshot
