### ISSUE TITLE
"Unexpected size change (...) You cannot modify files during a sync"

### ISSUE THREAD

**Issue by orangebutblue** [automorphism88/snapraid-btrfs#9]
I don't quite understand what I'm doing wrong, since I keep getting warnings about file-size changes.
How can these errors even occur if snapraid-btrfs uses snapshots?

Here is the execution log:

```
$ snapraid-btrfs --verbose -c /etc/snapraid.conf sync
snapraid-btrfs: WARNING: Running snapraid-btrfs as root is not recommended
Using snapraid config file /etc/snapraid.conf

SUBVOLUME for config root not found in /etc/snapraid.conf
Found /srv/dev-disk-by-label-wd30 in /etc/snapraid.conf - using snapper config wd30
Found /srv/dev-disk-by-label-wd31 in /etc/snapraid.conf - using snapper config wd31
Found /srv/dev-disk-by-label-wd10 in /etc/snapraid.conf - using snapper config wd10

Snapper configs found:
wd30 /srv/dev-disk-by-label-wd30/
wd30 /srv/dev-disk-by-label-wd30/
wd31 /srv/dev-disk-by-label-wd31/
wd31 /srv/dev-disk-by-label-wd31/
wd10 /srv/dev-disk-by-label-wd10/
wd10 /srv/dev-disk-by-label-wd10/

Created new snapshot 11 for config wd30
Using snapshot 11 for config wd30
Using snapshot 11 for config wd30
Created new snapshot 11 for config wd31
Using snapshot 11 for config wd31
Using snapshot 11 for config wd31
Created new snapshot 11 for config wd10
Using snapshot 11 for config wd10
Using snapshot 11 for config wd10

Using snapraid config file:

block_size 256
autosave 0

parity /srv/dev-disk-by-label-wdparity/snapraid.parity

content /srv/dev-disk-by-label-wd30/content/snapraid.content
disk wd30 /srv/dev-disk-by-label-wd30
content /srv/dev-disk-by-label-wd31/content/snapraid.content
disk wd31 /srv/dev-disk-by-label-wd31
content /srv/dev-disk-by-label-wd10/content/snapraid.content
disk wd10 /srv/dev-disk-by-label-wd10

exclude /.snapshots/
exclude /content/
exclude *.unrecoverable
exclude lost+found/
exclude aquota.user
exclude aquota.group
exclude /tmp/
exclude *.bak
exclude /snapraid.conf*
exclude /downloads/

snapraid -c /tmp/snapraid-btrfs.BeEJRt sync
Self test...
Loading state from /srv/dev-disk-by-label-wd30/content/snapraid.content...
Scanning disk wd30...
Scanning disk wd31...
Scanning disk wd10...
Using 940 MiB of memory for the file-system.
Initializing...
Resizing...
Saving state to /srv/dev-disk-by-label-wd30/content/snapraid.content...
Saving state to /srv/dev-disk-by-label-wd31/content/snapraid.content...
Saving state to /srv/dev-disk-by-label-wd10/content/snapraid.content...
Verifying /srv/dev-disk-by-label-wd30/content/snapraid.content...
Verifying /srv/dev-disk-by-label-wd31/content/snapraid.content...
Verifying /srv/dev-disk-by-label-wd10/content/snapraid.content...
Verified /srv/dev-disk-by-label-wd10/content/snapraid.content in 0 seconds
Verified /srv/dev-disk-by-label-wd31/content/snapraid.content in 1 seconds
Verified /srv/dev-disk-by-label-wd30/content/snapraid.content in 1 seconds
Syncing...
Using 32 MiB of memory for 32 cached blocks.
Unexpected size change at file '/srv/dev-disk-by-label-wd10/docker/plex/config/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.thetvdb.log.1' from 26986 to 15961.
WARNING! You cannot modify files during a sync.
Rerun the sync command when finished.
...
```

I also don't understand why it always prints the drive-related lines twice

```
Snapper configs found:
wd30 /srv/dev-disk-by-label-wd30/
wd30 /srv/dev-disk-by-label-wd30/
```

**Comment by automorphism88** [comment]
It definitely looks like it's not using the snapshots, since the config file it outputs when it says `Using snapraid config file:` is its modified one (`/tmp/snapraid-btrfs.BeEJRt` in your example) and it doesn't look like there are snapshot paths there. It's possible it's related to the duplicated output under `Snapper configs found:` since that doesn't happen for me either. The other difference I noticed between your configuration and mine is that it looks like your snapper configs have the same names as your drives in `snapraid.conf`. That should not make a difference, but could be worth seeing if it fixes your problem to change that.

Can you try running `snapraid-btrfs` with the `--debug` option and post the output? Also, post the output of `snapper get-config` for the configs `wd30`, `wd31`, and `wd10`. What version of snapper are you using, and are you using the latest snapraid-btrfs version?

**Comment by orangebutblue** [comment]
Thanks for the reply. I tried creating the log....however it's 5MB. I'm not sure if you even want to read the 5MB, but the upload limit on pastebin is 512kb :)

**Comment by automorphism88** [comment]
> Thanks for the reply. I tried creating the log....however it's 5MB. I'm not sure if you even want to read the 5MB, but the upload limit on pastebin is 512kb :)

It's not so much a matter of reading the entire 5MB as finding the important parts.

I guess GitHub allows file attachments now, so no need for pastebin. Maximum size is 25MB, and .gz is one of the accepted formats (the log should compress very well).

**Comment by orangebutblue** [comment]
There you go:
[debug.tar.gz](https://github.com/automorphism88/snapraid-btrfs/files/5520713/debug.tar.gz)

**Comment by automorphism88** [comment]
The duplicate config issue should be solved by a41a077b and the failure to use snapshots should be solved by 99d3e361. Please try with the latest commit and let me know what happens.

Protip: No need to use tar to compress a single file. Simply `gzip -9 debug.log` would have produced `debug.log.gz`.

**Comment by orangebutblue** [comment]
Amazing. It seems to be working now
Thank you.

**Comment by automorphism88** [comment]
No problem, thank you for reporting this and helping improve the script. Until recently, the script parsed the output of `snapper list-configs` to find subvolumes matching snapraid.conf, but a recent snapper update changed it so only root can run that command, so I had to hastily write some more complicated code to look in `/etc/snapper/configs` instead (since the script is designed to not be run as root). And it looks like that new code was broken in a couple of subtle ways that didn't have any effect with my own snapraid.conf file.

I'm going to go ahead and increment the version number due to the successful fix.

**Comment by orangebutblue** [comment]
I've noticed the "don't run as root" message, but I'm not sure  how I'm supposed to be doing that.
I created a dedicated snapchat user, but it doesn't seem to have the permissions to read the harddrive-contents.

do I have to do a chmod o+r on all of my files?

**Comment by automorphism88** [comment]
The user you run snapraid as needs to have permissions for all the files, yes (write as well as read, so you can run operations like fix). I wouldn't recommend doing chmod o+r, as it's unnecessary. You can set up permissions in multiple different ways, including just chowning all the files to your snapraid user. You could also use a snapraid group, chgrp everything to it, and set the setgid bit on all the directories (definitely better to give a group r/w permissions than world). You could also use ACLs.

All of that is outside the scope of this repo though, since the only difference with snapraid-btrfs versus snapraid is that you'll need to set up your snapraid user/group in your snapper configs (see the README). The snapraid documentation also recommends not running as root. It's not a snapraid-btrfs issue unless it works with "vanilla" snapraid and only has permission issues with snapraid-btrfs.
